<h1>Carrito de la compra</h1>

<ul class="list-group">
<?php foreach($cart as $transaction): ?>
    <li class="list-group-item item-task ">
    <div>
    <b>Usuario: <?= $transaction->user_name ?></b> (ID: <?= $transaction->user_id ?>) |
    <?php if ($transaction->Champion_id !== null): ?>
        Champion ID: <?= $transaction->ChampionName ?>
    <?php endif; ?> 
    <?php if ($transaction->Skin_id !== null): ?>
        Skin: <?= $transaction->SkinName ?>
    <?php endif; ?> |
    Precio: <?= $transaction->Monto ?>
</div>


        <div class="actions">
            <a href="eliminarTransaccion/<?= $transaction->Transaction_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>           
        </div>
    </li>
<?php endforeach ?>

</ul>

