<?php require 'templates/formAdd.phtml' ?>


<h1>Lista de campeones</h1>
<ul class="list-group">
<?php foreach($cats as $cats): ?>
    <li class="list-group-item item-task ">
        <div>
            <b><?= $cats->Champion_id ?></b> | <?=$cats->Nombre?> | (rol: <?= $cats->Rol ?>)  precio: <?= $cats->Precio ?>
 

        </div>
        <div class="actions">
            
            <?php
            if (isset($_SESSION['user_name']) && $_SESSION['user_name'] === 'admin') {  //Solo mostrara esto si el usuario logueado es el admin
            ?>
            <a href="eliminar/<?= $cats->Champion_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            <?php } ?>

            <a href="mostrar/<?= $cats->Champion_id ?>"  type="button" class="btn btn-success">Mostrar skins de este campeon</a>
            <a href="agregarTransaccionCampeon/<?= $cats->Champion_id?>/<?= $cats->Precio ?>"  type="button" class="btn btn-dark">Agregar al carrito</a>

            <?php require 'templates/formEditCat.phtml' ?>  <!--Muestra el form para editar la informacion de los campeones-->

        </div>
    </li>
    
<?php endforeach ?>
</ul>

<p class="mt-3"><small>-  Mostrando <?=$count?> campeones</small></p>





