<?php
if (isset($_SESSION['user_name']) && $_SESSION['user_name'] === 'webadmin') {  //Solo mostrara esto si el usuario logueado es el admin
?>

<h2>🡫🡫 Edicion de skin 🡫🡫</h2>
<form action="editarSkin/<?= $Skins->Skin_id ?>" method="POST" class="my-4">
    <div class="row">
    <div class="col-9">
        <div class="form-group">
            <input placeholder="Nuevo Nombre" required name="nombre" type="text" class="form-control">
        </div> 
    </div>
      
    <div class="col-4">
        <div class="form-group">
            <label>Nuevo precio</label>
                <select required name="Precio" class="form-control">
                    <option value="" disabled selected></option>
                    <option value="450">450</option>
                    <option value="1200">1200</option>
                    <option value="3500">3500</option>
                    <option value="4800">4800</option>
                    <option value="6300">6300</option>
                </select>
            </div> 
        </div>
    </div>

  

    <button type="submit" class="btn btn-warning">Actualizar</button>
</form>

<?php } ?>