<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
    <script src="http://localhost/tpe/assets/js/bootstrap.min.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Cba&Cba</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/headers/">
    <link rel="stylesheet" href="http://localhost/tpe/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://localhost/tpe/css/style.css">

    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Cba&Cba e-shop</a>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="http://localhost/tpe/listar">Pagina principal</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="http://localhost/tpe/listarTransacciones">Carrito de la compra</a>
          </li>

          <?php
            if (isset($_SESSION['user_name'])) {  //Con esto me aseguro de que el logout solo se muestre cuando haya una sesion iniciada
          ?>
            <li class="nav-item">
              <a class="nav-link" href="logout">LogOut (<?= $_SESSION['user_name'] ?>)</a>
            </li>
          <?php } ?>

        </ul>

      </div>
    </div>
  </nav>
</body>

</body>