<h1>Lista de skins</h1>
<ul class="list-group">
<?php foreach($Skins as $Skins): ?>
    <li class="list-group-item item-task ">
        <div>
            <?=$Skins->ChampionName?> | <?=$Skins->SkinName?> |   Precio: <?= $Skins->Precio ?>
        </div>
        <div class="actions">
            
            <?php
            if (isset($_SESSION['user_name']) && $_SESSION['user_name'] === 'webadmin') {  //Solo mostrara esto si el usuario logueado es el admin
            ?>
            <a href="eliminarSkin/<?= $Skins->Skin_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            <?php } ?>

            <a href="agregarTransaccionSkin/<?= $Skins->Skin_id?>/<?= $Skins->Precio ?>"  type="button" class="btn btn-dark">Agregar al carrito</a>

            <a href="verDetalleSkin/<?= $Skins->Skin_id?>"  type="button" class="btn btn-info">Ver detalle</a>

            <?php require 'templates/formEditSkin.phtml' ?>  <!--Muestra el form para editar la informacion de los skins-->

        </div>
    </li>
    
<?php endforeach ?>
</ul>

<p class="mt-3"><small>-  Mostrando <?=$count?> skins</small></p>





